// Auto-generated by Rapida Vibe. Do not edit manually.
import type { RouteRecordRaw } from "vue-router";

// Dynamically imported components generated by Rapida Vibe
// ⚠️ This block will be populated automatically
// Example:
// import MyForm from "@/components/forms/my-form.vue";

export const generatedRoutes: RouteRecordRaw[] = [
  // ⚠️ This block will be populated automatically
  // Example:
  // {
  //   path: "/my-form",
  //   name: "MyForm",
  //   component: MyForm,
  // },
];
